baseurl: https://aureliendossantos.github.io/
languageCode: fr-fr
theme: animus # hugo-theme-stack
paginate: 10
title: Aur√©lien Dos Santos

# Build timeout (parce que les images prennent du temps)
timeout: 600000
# GA Tracking ID
googleAnalytics:
# Theme i18n support
DefaultContentLanguage: fr

#permalinks:
#    post: /post/:slug/
#    page: /:slug/
